/** 业务表中文说明（与 backend BUSINESS_TABLE_DESCRIPTIONS 保持一致） */
export const TABLE_LABELS: Record<string, string> = {
  users: '用户账号',
  conversations: '聊天会话',
  conversation_members: '会话成员',
  messages: '聊天消息',
  friendships: '好友关系',
  friend_requests: '好友申请',
  group_join_requests: '入群申请',
  group_blacklist: '群黑名单',
  notifications: '系统通知',
  ai_bots: 'AI 机器人',
  group_ai_bots: '群 AI 机器人',
  moments: '说说动态',
  moment_likes: '说说点赞',
  moment_comments: '说说评论',
  user_reports: '用户举报',
  draw_guess_group_scores: '你画我猜积分',
  avatar_frames: '头像框目录',
  avatar_frame_activation_codes: '头像框激活码',
  user_avatar_frames: '用户已解锁头像框',
  chat_bubbles: '聊天气泡目录',
  bubble_activation_codes: '气泡激活码',
  user_chat_bubbles: '用户已解锁气泡'
}

/** 常见字段中文说明 */
export const COLUMN_LABELS: Record<string, string> = {
  id: '主键',
  chat_no: '聊聊号',
  username: '用户名',
  nickname: '昵称',
  password_hash: '密码哈希',
  avatar_url: '头像地址',
  status: '状态',
  created_at: '创建时间',
  updated_at: '更新时间',
  user_id: '用户 ID',
  sender_id: '发送者 ID',
  receiver_id: '接收者 ID',
  conversation_id: '会话 ID',
  friend_id: '好友 ID',
  content: '内容',
  message_type: '消息类型',
  conv_type: '会话类型',
  title: '标题',
  name: '名称',
  description: '描述',
  email: '邮箱',
  phone: '手机号',
  is_banned: '是否封禁',
  is_admin: '是否管理员',
  role: '角色',
  joined_at: '加入时间',
  read_at: '已读时间',
  expires_at: '过期时间',
  register_ip: '注册 IP',
  last_login_at: '最后登录',
  bot_id: '机器人 ID',
  group_id: '群 ID',
  room_id: '聊天室 ID',
  banned_until: '封禁截止',
  reason: '原因',
  type: '类型',
  payload: '附加数据',
  is_read: '是否已读',
  from_user_id: '发起用户',
  to_user_id: '目标用户',
  actor_user_id: '操作者',
  related_id: '关联 ID',
  moment_id: '说说 ID',
  frame_id: '头像框 ID',
  bubble_id: '气泡 ID',
  frame_url: '头像框图片',
  is_free: '是否免费',
  enabled: '是否启用',
  sort_order: '排序',
  code: '激活码',
  used_by: '使用者',
  used_at: '使用时间',
  unlocked_at: '解锁时间',
  source: '来源',
  reporter_id: '举报人',
  target_user_id: '被举报人',
  detail: '详情',
  images_json: '图片 JSON',
  admin_note: '管理员备注',
  handled_at: '处理时间',
  voice_url: '语音地址',
  voice_duration: '语音时长',
  image_url: '图片地址',
  is_self: '是否本人',
  category: '分类',
  is_decorated: '是否装饰气泡',
  preview_text: '预览文案',
  total_score: '总分',
  scale: '缩放',
  offset_x_pct: 'X 偏移%',
  offset_y_pct: 'Y 偏移%',
  hole_diameter_ratio: '挖孔比例'
}

export function tableLabel(name: string, desc?: string) {
  return desc || TABLE_LABELS[name] || ''
}

export function columnLabel(name: string) {
  return COLUMN_LABELS[name] || ''
}
